interface config {
    GET_VALUES: String;
    userList: string;
    LOGIN_ADMIN: string;
    BASE_URL: string;
    CREATE_USER: string;
    CREATE_ADMIN: string;
    AUTH_USER: string;
    CREATE_WAVE: string;
    GET_MY_WAVES: string;
    GET_REQUESTS: string;
    INVITE_FRIEND: string;
    SECRET_KEY: string;
    GET_LATEST_WAVES: string;
    GET_COMMENTS: string;
    GET_PREFERENCE: string;
    UPDATE_PREFERENCE: string;
    UPDATE_PROFILE: string;
    EDIT_PASSWORD: string;
    GET_FRIENDS: string;
    ADD_COMMENT: string;
    EDIT_COMMENT: string;
    DELETE_COMMENT: string;
    ADMIN_LOGOUT: string;
    UPDATE_WAVE_STATUS: string;
    UPDATE_USER_STATUS: string
    UPDATE_USER: string;
    GET_ALL_USERS: string;
    GET_ALL_WAVES: string;
    PERSONAL_UPDATE_USER: string;
    BASIC_UPDATE_USER: string;
    DELETE_USER: string;
    DELETE_WAVE: string;
}
const Local: config = {
    BASE_URL: import.meta.env.VITE_BASE_URL,
    userList: '/getfriendlist',
    CREATE_USER: '/signup',
    CREATE_ADMIN: '/admin-register',
    LOGIN_ADMIN: '/admin-login',
    AUTH_USER: 'login',
    CREATE_WAVE: '/addwave',
    GET_MY_WAVES: '/getmywave',
    GET_REQUESTS: '/getrequests',
    INVITE_FRIEND: '/invite-friend',
    SECRET_KEY: 'dK2JG6hi7ghH7HfuiytbkU7578PmbhJGJok3r43',
    GET_LATEST_WAVES: '/getlatestwaves',
    GET_COMMENTS: '/getcomments',
    GET_PREFERENCE: '/getpreference',
    UPDATE_PREFERENCE: '/updatepreference',
    UPDATE_PROFILE: '/updateprofile',
    EDIT_PASSWORD: '/updatepassword',
    GET_FRIENDS: '/getfriendlist',
    ADD_COMMENT: '/addcomment',
    EDIT_COMMENT: '/editcomment',
    DELETE_COMMENT: '/deletecomment',
    ADMIN_LOGOUT: '/adminlogout',
    UPDATE_WAVE_STATUS: '/editwavestatus',
    UPDATE_USER_STATUS: '/edituserstatus',
    UPDATE_USER: '/updateUser',
    GET_ALL_USERS: '/allusers',
    GET_ALL_WAVES: '/allwaves',
    GET_VALUES: '/getdata',
    PERSONAL_UPDATE_USER: '/editadminpersonaluser',
    BASIC_UPDATE_USER: '/editadminbasicuser',
    DELETE_USER: '/deleteuser',
    DELETE_WAVE: '/deletewave',
}

export default Local